### ISSUE TITLE
Please license the project

### ISSUE THREAD

**Issue by erikh** [rendon/clitesting#3]
Presuming this is open source, I'd like to make sure I can legally use it. If you want, I can send a PR with the license of your choice appropriately edited for you.

I hope these requests aren't a problem!

**Comment by rendon** [comment]
@erikh Yeah, it's open source, I'm going to add a license, I was thinking MIT, what do you think?

**Comment by erikh** [comment]
SGTM. I usually use MIT or Apache too.

**Comment by rendon** [comment]
@erikh Done!

**Comment by erikh** [comment]
thanks!
