### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by rvasilevsf** [rendon/clitesting#5]
Thanks for sharing this with the community!
Do you mind tagging a release vx.y.z so it could be easily distinguishable in the go.mod files?

**Comment by rendon** [comment]
Hi @rvasilevsf, I wouldn't mind doing it if you share more details about it, when I wrote this code Go didn't support modules.

**Comment by rvasilevsf** [comment]
Just create a git tag off master in the form vX.Y.Z, example v1.0.0. Thanks!

**Comment by rendon** [comment]
I forgot about this issue until now. @rvasilevsf is https://github.com/rendon/testcli/releases/tag/v1.0.0 what you had in mind?

**Comment by rvasilevsf** [comment]
indeed that was. thank you.
